<#
Cava P0-E: install a datapack that can summon a fixed number of mobs with one command.
Used by the "loaded" performance baseline: /function cava:spawn_mobs

The positions are a fixed grid around the world spawn (spawn is 0,~,0 for the generated
base world), so the entity load is reproducible run to run.

usage: pwsh -File tools/make-load-datapack.ps1 -WorldDir <world> -Count 200
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][string]$WorldDir,
  [int]$Count = 200,
  [string]$EntityType = 'minecraft:zombie',
  [string]$Name = 'cava-load',
  [double]$Y = 78
)
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
if (-not (Test-Path -LiteralPath $WorldDir)) { throw "world dir not found: $WorldDir" }
$base = Join-Path $WorldDir ("datapacks\" + $Name)
New-Item -ItemType Directory -Force -Path (Join-Path $base 'data\cava\functions') | Out-Null
'{"pack":{"pack_format":26,"description":"Cava P0-E entity load harness"}}' |
  Set-Content -Encoding ASCII (Join-Path $base 'pack.mcmeta')

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# generated by tools/make-load-datapack.ps1 -- deterministic grid around world spawn')
for ($i = 0; $i -lt $Count; $i++) {
  $x = -25 + ($i % 20) * 2.5
  $z = -25 + [math]::Floor($i / 20) * 5.0
  $lines.Add(("summon {0} {1} {2} {3} {{PersistenceRequired:1b,Tags:[""cava_load""]}}" -f $EntityType, $x.ToString([System.Globalization.CultureInfo]::InvariantCulture), $Y, $z.ToString([System.Globalization.CultureInfo]::InvariantCulture)))
}
$lines | Set-Content -Encoding ASCII (Join-Path $base 'data\cava\functions\spawn_mobs.mcfunction')
Write-Host ("[load-datapack] installed $base : {0} x {1} at y={2}" -f $Count, $EntityType, $Y)
