<#
Cava P0-E: provision a real Fabric dedicated server testbed inside the workspace.

What it does (idempotent, safe to re-run):
  1. resolves the Fabric loader/installer version for the MC version from meta.fabricmc.net (via node)
  2. downloads the Fabric server launcher jar  -> testbed\dl\
  3. downloads the vanilla server jar from piston-meta (sha1 verified) -> testbed\server\server.jar
  4. writes deterministic eula.txt / server.properties / fabric-server-launcher.properties
  5. stages mods according to the three-tier policy (tools/copy-mods.ps1)

Network goes through node (PowerShell Invoke-WebRequest fails TLS on this host).
Nothing here is committed: testbed/ is in .gitignore.

usage:
  pwsh -File tools/setup-testbed.ps1                 # wave 4 = full "keep" set
  pwsh -File tools/setup-testbed.ps1 -Wave 0         # fabric-api + spark only
  pwsh -File tools/setup-testbed.ps1 -Force          # re-download jars
#>
[CmdletBinding()]
param(
  [string]$McVersion = '1.20.4',
  [string]$Root = '',
  [int]$Wave = 4,
  [string]$Profile = '',
  [string]$Probe = '',
  [int]$ServerPort = 25566,
  [int]$RconPort = 25576,
  [switch]$Force,
  [switch]$NoMods,
  [string]$NodeExe = 'C:\Program Files\nodejs\node.exe',
  [long]$Seed = 20260922
)
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
if (-not $Root) { $Root = Join-Path (Split-Path $PSScriptRoot -Parent) 'testbed' }
$Root = [System.IO.Path]::GetFullPath($Root)
$dl = Join-Path $Root 'dl'
$server = Join-Path $Root 'server'
New-Item -ItemType Directory -Force -Path $dl, $server, (Join-Path $server 'mods') | Out-Null

# --- 1. resolve versions --------------------------------------------------
$metaRaw = & $NodeExe (Join-Path $PSScriptRoot 'meta.cjs') $McVersion
if ($LASTEXITCODE -ne 0) { throw 'meta.cjs failed' }
$meta = @{}
foreach ($line in $metaRaw) { if ($line -match '^([a-z_]+)=(.*)$') { $meta[$Matches[1]] = $Matches[2] } }
$loader = $meta['loader']; $installer = $meta['installer']; $url = $meta['server_launcher_url']
Write-Host "[setup] mc=$McVersion loader=$loader installer=$installer"
Write-Host "[setup] launcher url=$url"

# --- 2. fabric server launcher -------------------------------------------
$launcher = Join-Path $dl ("fabric-server-mc{0}-loader{1}-installer{2}.jar" -f $McVersion, $loader, $installer)
if ($Force -or -not (Test-Path $launcher) -or (Get-Item $launcher).Length -lt 10000) {
  & $NodeExe (Join-Path $PSScriptRoot 'dl.cjs') $url $launcher
  if ($LASTEXITCODE -ne 0) { throw 'launcher download failed' }
} else { Write-Host "[setup] launcher already present: $launcher" }

# --- 3. vanilla server jar ------------------------------------------------
$serverJar = Join-Path $server 'server.jar'
if ($Force -or -not (Test-Path $serverJar) -or (Get-Item $serverJar).Length -lt 1000000) {
  $van = & $NodeExe (Join-Path $PSScriptRoot 'get-vanilla.cjs') $McVersion $serverJar
  if ($LASTEXITCODE -ne 0) { throw 'vanilla server download failed' }
  ($van | Where-Object { $_ -match '^sha1_match=' }) | ForEach-Object { Write-Host "[setup] $_" }
} else { Write-Host "[setup] vanilla server.jar already present ($((Get-Item $serverJar).Length) bytes)" }

# --- 4. deterministic config ---------------------------------------------
$eula = Join-Path $server 'eula.txt'
@"
# Generated by tools/setup-testbed.ps1
eula=true
"@ | Set-Content -Encoding ASCII $eula

$launcherProps = Join-Path $server 'fabric-server-launcher.properties'
@"
# Generated by tools/setup-testbed.ps1
serverJar=server.jar
"@ | Set-Content -Encoding ASCII $launcherProps

# Deterministic server.properties. Deliberate choices are marked.
$props = @"
# Generated by tools/setup-testbed.ps1 -- do not hand edit, re-run the script instead.
# frozen-for-baseline: level-seed / level-type / randomTickSpeed / difficulty / view+sim distance
allow-flight=true
allow-nether=true
difficulty=normal
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=false
force-gamemode=false
function-permission-level=4
gamemode=creative
generate-structures=true
hardcore=false
level-name=world
level-seed=$Seed
level-type=minecraft:normal
max-players=20
max-tick-time=-1
max-world-size=29999984
motd=Cava P0-E testbed
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=$ServerPort
randomTickSpeed=3
rate-limit=0
rcon.password=cava
rcon.port=$RconPort
require-resource-pack=false
server-ip=
server-port=$ServerPort
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
sync-chunk-writes=true
view-distance=10
white-list=false
"@
$props | Set-Content -Encoding ASCII (Join-Path $server 'server.properties')

# no players are ever white-listed, but ops.json/whitelist.json are pinned empty for determinism
'[]' | Set-Content -Encoding ASCII (Join-Path $server 'ops.json')
'[]' | Set-Content -Encoding ASCII (Join-Path $server 'whitelist.json')

# --- 5. mods --------------------------------------------------------------
if (-not $NoMods) {
  & (Join-Path $PSScriptRoot 'copy-mods.ps1') -Wave $Wave -Profile $Profile -Probe $Probe
  if ($LASTEXITCODE -ne 0 -and $null -ne $LASTEXITCODE) { throw 'copy-mods.ps1 failed' }
}
$modCount = (Get-ChildItem (Join-Path $server 'mods') -Filter *.jar).Count
Write-Host ""
Write-Host "[setup] DONE  root=$Root"
Write-Host "[setup]   launcher   = $launcher"
Write-Host "[setup]   server.jar = $serverJar"
Write-Host "[setup]   mods staged= $modCount  (wave=$Wave profile='$Profile' probe='$Probe')"
Write-Host "[setup]   rcon       = 127.0.0.1:25576 password=cava   (game port 25566; 25565/25575 are used by other agents)"
Write-Host "[setup] next: pwsh -File tools/start-server.ps1 -Name smoke -MaxSeconds 180"
